% CONFIDENTIAL (C) Mitsubishi Electric Research Labs (MERL) 2018
% Author: Kaivalya Bakshi; Date: 24 Apr 2018; Function for computing
% dynamics of soliton position and momentum ODEs for Hamiltonian system  
% described in MERL report based on Quadratic MFG paper by Ullmo et. al
% (https://arxiv.org/pdf/1708.07730.pdf). We extend the published example 
% by admitting coupled and non trivial passive drift in the SDE dynamics
function dXdt = SolitonDyn(t,X)

global mu sigma par c % c = 0/1 for uncoupled/coupled pos, var dynamics

q1 = X(1,1); p1 = X(2,1); q2 = X(3,1); p2 = X(4,1); g = par.g; alpha = par.alpha;
k = g/(1+alpha)/sqrt(1 + alpha)/(2*pi)^(alpha/2);

% % 1D integrator system with U0 = -x^4/4 - x^2/2
% dXdt = [p1/mu; ...
%         q1^3 + (1 + c*3*q2^2)*q1; ...
%         p2/mu; ...
%         -mu*sigma^4/(4*q2^3) + k*alpha/q2^(alpha+1) ...
%         - c*q2*(-3*(q1^2 + q2^2) - 1)]; 
    
% 1D overdamped Langevin dynamics with nu = x^4/4 - x^2/2 and U0 = ku(x -
% 1)^2/2
ku = 1;
dXdt = [p1/mu; ...
        ku*(q1 - 1) + 3*(q1^5 + 10*q1^3*c*q2^2 + 15*q1*c*q2^4) ...
                    - 4*(q1^3 + 3*q1*c*q2^2) ...
                    + q1*(1 - 3*sigma^2);
        p2/mu; ...
        -mu*sigma^4/(4*q2^3) + k*alpha/q2^(alpha+1) ...
        - c*q2*( ku ...
        + 15*(q1^4 + 6*q1^2*q2^2 + 3*q2^4) ...
        - 12*(q1^2 + q2^2) ...
        + (1 - 3*sigma^2) )];
    
% dXdt = [X(2,1)/mu + par.alpha*(-X(1,1)^3 + X(1,1)); X(1,1)^3 + X(1,1)]; % linear passive drift
% dXdt = [X(2,1)/mu + par.alpha*sin(X(1,1)); X(1,1)^3 + X(1,1)]; % trigonometric drift
% dXdt = [X(2,1)/mu + par.alpha*(-X(1,1)^3 + X(1,1)); X(1,1)^3 + X(1,1)]; % bistable potential passive drift
end